### ISSUE TITLE
pip asks for sudo password

### ISSUE THREAD

**Issue by Dapid** [gersolar/netcdf#18]
I am trying to update netcdf in a virtual environment on Fedora, but it asks me for my sudo password, that I don't have. 

     (py27)[david@SQUIDS ~]$ pip install -U netcdf
     Collecting netcdf
       Downloading netcdf-0.1.3.tar.gz (16.5MB)
         100% |████████████████████████████████| 16.5MB 35kB/s 

     [...some compilling...]

     [sudo] password for david: 
     Operation cancelled by user

Netcdf libraries are installed:

    (py27)[root@SQUIDS david]# yum list installed | grep netcdf
    netcdf.x86_64              4.3.2-5.fc21             @fedora                     
    netcdf-cxx.x86_64          4.2-11.fc21              @fedora                     
    netcdf-cxx-devel.x86_64    4.2-11.fc21              @fedora                     
    netcdf-cxx4.x86_64         4.2.1-4.fc21             @fedora                     
    netcdf-cxx4-devel.x86_64   4.2.1-4.fc21             @fedora                     
    netcdf-devel.x86_64        4.3.2-5.fc21             @fedora

**Comment by ecolell** [comment]
Hi,

Yes, It tryed to compile the **libhdf5** and the **libnetcdf** from sources if you don't have any of the next files:
**/usr/local/lib**/libhdf5.so.8.0.1
**/usr/local/lib**/libnetcdf.so.7.2.0.

I never tested on Fedora, but as an alternantive you should try to install the yum packages: [netcdf-mpich (4.3.2)](http://rpm.pbone.net/index.php3/stat/4/idpl/28285994/dir/fedora_21/com/netcdf-mpich-4.3.2-5.fc21.x86_64.rpm.html) and [hdf5-mpich (1.8.12)](http://arm.koji.fedoraproject.org/koji/rpminfo?buildrootOrder=id&rpmID=1034398&fileOrder=name&fileStart=0) that contain the needed files.

Then you need to copy those files to the /usr/local/bin:

    # cp /usr/local/lib/libhdf5.so.8* /usr/local/lib/
    # cp /usr/lib64/mpich/lib/libnetcdf.so.7* /usr/local/lib/ 

Last, when you do:

    pip install -U netcdf

It shouldn't ask for the sudo password again.
Let me know if it worked.

**Comment by Dapid** [comment]
I see, I have `/usr/local/lib/libhdf5.so.8.0.2` and the right libnetcdf. Installing the suggested packages doesn't help, because of the version mismatch.

Does necdf require down to the minor version matching?

**Comment by ecolell** [comment]
I don't think the minor version do the difference :+1:  but the [setup.py](https://github.com/gersolar/netcdf/blob/master/setup.py) need to check for an specific version. It need a way to check if it should to compile the library or not.

You can try a **monky patch** to avoid the **sudo access**. Make a copy of those files your system have to match the specific requirements of the netcdf, and try to pip again (maybe it work :+1:).

Other option is to manually compile the **netcdf** and the **hdf5** libraries from the sourcecode:
* [ftp://ftp.unidata.ucar.edu/pub/netcdf](ftp://ftp.unidata.ucar.edu/pub/netcdf)
* [http://www.hdfgroup.org/ftp/HDF5/releases/](http://www.hdfgroup.org/ftp/HDF5/releases/)

**Comment by gshamov** [comment]
This is very troblesome behaviour because on many many HPC systems, /usr nor /usr/local is not the destination for application software like HDF5. A code should not assume any fixed location or that HDF5 is installed via OS mechanism (like apt-get or rpm); LD_LIBRARY_PATH should be searched instead.

**Comment by ecolell** [comment]
@gshamov You are right. I don't taked that into account when I've worked on this. Right now it is impossible to me to fix this. But you are welcome, I could deploy the fix to pypi (y).
