### ISSUE TITLE
[RFE] python3 support

### ISSUE THREAD

**Issue by ignatenkobrain** [gersolar/netcdf#21]
would be great if you will add support for python3. We're working on Fedora for NeuroImaging and netcdf will be used there, but we want to ship python2 and python3 versions in the same time.

**Comment by ignatenkobrain** [comment]
```python
+ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
  File "setup.py", line 132
    print '\r%s' % (' ' * 78),
               ^
SyntaxError: invalid syntax
```

This is only one of ton of errors...

**Comment by ecolell** [comment]
Hi! I'll made a new commit to the master:

- replacing all the string formating in the setup.py and netcdf/netcdf.py.
- replacing the print statement for the __future__.print_function.

Let me know if there is anything else that fails, and i'll try to fixit to work for your environment.

**Comment by ecolell** [comment]
Well, the release of the [version 0.2.0](https://pypi.python.org/pypi/netcdf/0.2.0) deploy and pass unit tests with python3.4.

`pip install netcdf>=0.2.0`

**Comment by shaief** [comment]
@ecolell , i still can't install it using Python3 due to the following error:
```
Collecting netcdf
  Downloading netcdf-0.2.0.tar.gz (16.5MB)
    100% |████████████████████████████████| 16.5MB 19kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-10lpm8tg/netcdf/setup.py", line 9, in <module>
        from urllib import urlretrieve
    ImportError: cannot import name 'urlretrieve'
```
`urlretrieve` moved to live under `urllib.request`.

**Comment by ecolell** [comment]
@shaief What specific version of python3 are you using?

**Comment by shaief** [comment]
Python 3.5.0

**Comment by ecolell** [comment]
Well, today I appended all the version python to the [travis-ci service and it work find in all the versions](https://travis-ci.org/gersolar/netcdf/builds/95185143) (included 3.5.0).

But, in the other hand, I made a [new commit](https://travis-ci.org/gersolar/netcdf/builds/95224068) to import the urlretrieve in the right way according the python version (If it pass the tests I'll release the version 0.2.1).

**Comment by shaief** [comment]
Thanks!

**Comment by ecolell** [comment]
Thanks to you! The release 0.2.1 (cae82225be98586d7516bbfc5aafa8f2a2b266c4) try to solve this issue.
