### ISSUE TITLE
I can't get the variables

### ISSUE THREAD

**Issue by liuxiaoer** [gersolar/netcdf#5]
When i open the ncfile,I can't get the varialbes

root, is_new = nc.open('/mnt/tmp/a.nc')
>>> root.variables
{}
and then I called " root.getvar('area')"
and showed variables like below:
>>> root.variables
{ 'area': &lt;netcdf.netcdf.SingleNCVariable object at 0x1d67a50&gt;}

How can I get the variables after I opened the NCFile?

**Comment by ecolell** [comment]
Hi, you also should include the root variable as the first argument of the nc.getvar:

    area = nc.getvar(root, 'area')

Then, from a SingleNCVariable you can obtain a numpy matrix when you select with squared brakets:

    print area[:]
    area_squared = area[:] ** 2
